NT_project:
  outputs:
    dev:
      account: snugdpc-jr42519
      database: dora_playground
      password: dnadev2024
      role: dnadev_role
      schema: public
      threads: 1
      type: snowflake
      user: dnadev_user
      warehouse: playground_wh
  target: dev
